---
- name: Create AWS Key Pair
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    key_name: kptest1
    key_path: "kptest1"

  tasks:
    - name: Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        force: true
      register: key_pair

    - name: Save Private Key
      copy:
        content: "{{ key_pair.key.private_key | to_bytes | b64decode }}"
        dest: "{{ key_path }}.pem"
        mode: 0400

    - name: Decrypt Private Key
      openssl_privatekey:
        path: "{{ key_path }}.pem"
        decrypt: yes
        # passphrase: "{{ private_key_password }}"
        dest: "{{ key_path }}_decrypted.pem"

    - name: Display Key Pair
      debug:
        var: key_pair
