---
- name: Create AWS Key Pair
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    key_name: my_key

  tasks:
    - name: Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      register: key_pair

    - name: Display Key Pair
      debug:
        var: key_pair

