 ---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    ami_id: "ami-04132f301c3e4f138"  # Specify the AMI ID for the desired Amazon Machine Image
    key_pair: "kptest"  # Specify the name of your key pair
    security_group: "vpc-09b904307a5fdd1c6"  # Specify the name of your security group
    ansible_aws_access_key: "AKIAQEHZAVZBUIPP72GL"
    ansible_aws_secret_key:"d6G0sJLpFYGrLD7yusg10iCjSamFsR3"
    #ansible_aws_security_token:
    
  tasks:
    - name: Configure AWS connection
      local_action:
        module: ec2
        region: "{{ region }}"
        aws_access_key: "{{ ansible_aws_access_key }}"
        aws_secret_key: "{{ ansible_aws_secret_key }}"
        #security_token: "{{ ansible_aws_security_token }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_pair }}"
        group: "{{ security_group }}"
        count: 1
        wait: true
        instance_tags:
          Name: "My EC2 Instance"
      register: ec2_instance

    - name: Show instance details
      debug:
        var: ec2_instance.instances[0]
