---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    ami_id: "ami-04132f301c3e4f138"  # Specify the AMI ID for the desired Amazon Machine Image
    key_pair: "kptest"  # Specify the name of your key pair
    security_group: "vpc-09b904307a5fdd1c6"  # Specify the name of your security group
  tasks:
    - name: Launch EC2 instance
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        group: "{{ security_group }}"
        count: 1
        wait: true
        instance_tags:
          Name: "My EC2 Instance"
      register: ec2_instance

    - name: Show instance details
      debug:
        var: ec2_instance.instances[0]
